In [1]:
import numpy as np

In [12]:
A = np.array([
    [60, 5.5, 1],
    [65, 5.0, 0],
    [55, 6.0, 1],
    [50, 5.0, 1]
    ])
b = np.array([[66, 74, 78, 72]])
b.reshape(-1, 1)

A.shape, b.shape

((4, 3), (1, 4))

In [13]:
def least_squares(A, b):
    return np.linalg.inv(np.dot(A.T, A)) @ A.T @ b.T

In [14]:
least_squares(A, b)

array([[ -0.15231317],
       [ 16.58362989],
       [-10.83274021]])

In [41]:
def gram_schmidt(A):
    A[:, 0] /= np.linalg.norm(A[:, 0])
    for i in range(1, A.shape[1]):
        for j in range(i):
            A[:, i] -= (np.dot(A[:, i], A[:, j]) / (np.dot(A[:, j], A[:, j]))) * A[:, j]
        A[:, i] /= np.linalg.norm(A[:, i])
    return A

In [51]:
A = np.array([
    [1.0, 2.0, 3.0],
    [-1.0, 0.0, -3.0],
    [0.0, -2.0, 3.0]
])

Q = gram_schmidt(A)
Q

array([[ 0.70710678,  0.40824829,  0.57735027],
       [-0.70710678,  0.40824829,  0.57735027],
       [ 0.        , -0.81649658,  0.57735027]])

In [50]:
Q.T @ Q

array([[ 1.00000000e+00,  2.45142679e-17, -1.77961928e-17],
       [ 2.45142679e-17,  1.00000000e+00, -2.21943272e-17],
       [-1.77961928e-17, -2.21943272e-17,  1.00000000e+00]])

In [53]:
def qr_decomposition(A):
    Q = gram_schmidt(A)
    R = Q.T @ A
    return Q, R

In [54]:
A = np.array([
    [1, 0, 0],
    [1, 1, 0],
    [1, 1, 1],
    [1, 1, 1]
], dtype=float)

Q, R = qr_decomposition(A)
Q, R

(array([[ 0.5       , -0.8660254 ,  0.        ],
        [ 0.5       ,  0.28867513, -0.81649658],
        [ 0.5       ,  0.28867513,  0.40824829],
        [ 0.5       ,  0.28867513,  0.40824829]]),
 array([[ 1.00000000e+00,  5.55111512e-17, -5.55111512e-17],
        [ 5.55111512e-17,  1.00000000e+00, -2.43538951e-17],
        [-5.55111512e-17, -2.43538951e-17,  1.00000000e+00]]))

In [21]:
numpy_q, numpy_r = np.linalg.qr(A)

In [25]:
numpy_r

array([[-1.00000000e+00, -1.11022302e-16,  9.43406321e-17],
       [ 0.00000000e+00, -1.00000000e+00,  2.22044605e-16],
       [ 0.00000000e+00,  0.00000000e+00, -1.00000000e+00]])